//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.14 at 10:53:25 PM ART 
//


package ar.edu.ubp.das.rest.soap;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ar.edu.ubp.das.rest.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetTiposServicios_QNAME = new QName("http://ws.das.ubp.edu.ar/", "getTiposServicios");
    private final static QName _GetTiposServiciosResponse_QNAME = new QName("http://ws.das.ubp.edu.ar/", "getTiposServiciosResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ar.edu.ubp.das.rest.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetTiposServicios }
     * 
     */
    public GetTiposServicios createGetTiposServicios() {
        return new GetTiposServicios();
    }

    /**
     * Create an instance of {@link GetTiposServiciosResponse }
     * 
     */
    public GetTiposServiciosResponse createGetTiposServiciosResponse() {
        return new GetTiposServiciosResponse();
    }

    /**
     * Create an instance of {@link TipoServicioBean }
     * 
     */
    public TipoServicioBean createTipoServicioBean() {
        return new TipoServicioBean();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTiposServicios }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetTiposServicios }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.das.ubp.edu.ar/", name = "getTiposServicios")
    public JAXBElement<GetTiposServicios> createGetTiposServicios(GetTiposServicios value) {
        return new JAXBElement<GetTiposServicios>(_GetTiposServicios_QNAME, GetTiposServicios.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTiposServiciosResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetTiposServiciosResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.das.ubp.edu.ar/", name = "getTiposServiciosResponse")
    public JAXBElement<GetTiposServiciosResponse> createGetTiposServiciosResponse(GetTiposServiciosResponse value) {
        return new JAXBElement<GetTiposServiciosResponse>(_GetTiposServiciosResponse_QNAME, GetTiposServiciosResponse.class, null, value);
    }

}
