//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.15 at 12:33:35 AM ART 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.das.ubp.edu.ar/")
package ar.edu.ubp.das.rest.soap;
